function add(a,b){
   return a+b;
}


console.log(add(40,80))
// add(40,80)

let result =add(40,60)
console.log(result/ 5)
result=add(30,60)
console.log(add(30,70))
console.log(add(3,70))
console.log(add(30,20))
console.log(add(40,80))
console.log(add(90,70))
console.log(add(320,30))



// function expresion 

let sum = function(a,b){

return a+b;

}
console.log(sum(30,60))
console.log(sum(50,60))
console.log(sum(3,60))
console.log(sum(30,90))
console.log(sum(30,60))
console.log(sum(30,50))
console.log(sum(55,60))
console.log(sum(30,67))



//  fuction expresion add wuu iga diidey sidaa awgeed waxaan isticmaaley sum